/** Dev-only capture stage. Uses the game's real geometry/materials and matched framing per pair. */
import * as THREE from 'three';
import { HULLS, ORIGINAL_HULLS } from '@/ships/hulls';
import { BOMBER_REVISED } from '@/combat/bomber-def';
import { buildShip } from '@/ships/builder';
import { disposeTree } from '@/render/dispose';
import { Capital } from '@/combat/capital';

const q = new URLSearchParams(location.search);
const candidates: typeof HULLS = {...HULLS, bomber:BOMBER_REVISED};
const key = q.get('hull') ?? 'glider';
const old = q.get('version') === 'original';
const view = q.get('view') ?? 'perspective';
const silhouette = view === 'silhouette';
const scene = new THREE.Scene();
scene.background = new THREE.Color(silhouette ? 0xe9edf0 : 0x111820);
const group = key === 'capital' ? new Capital({originalArt:old}).group : buildShip((old ? ORIGINAL_HULLS[key] : candidates[key])!);
const other = key === 'capital' ? new Capital({originalArt:!old}).group : buildShip((old ? candidates[key] : ORIGINAL_HULLS[key])!);
const bounds = new THREE.Box3().setFromObject(group).union(new THREE.Box3().setFromObject(other));
const center = bounds.getCenter(new THREE.Vector3());
const size = bounds.getSize(new THREE.Vector3());
disposeTree(other);
scene.add(group);
if (silhouette) group.traverse(o => {if (o instanceof THREE.Mesh) {if(o.name==='outline'||o.name==='decal') o.visible=false; else o.material = new THREE.MeshBasicMaterial({color:0x111820});}});
const keyLight = new THREE.DirectionalLight(0xfff3db,2.7); keyLight.position.set(60,90,100); scene.add(keyLight);
scene.add(new THREE.HemisphereLight(0xc3d8f5,0x465365,1.2));
const rim = new THREE.DirectionalLight(0x91b8df,1.1);rim.position.set(-60,20,-70);scene.add(rim);
const extent = Math.max(size.x,size.y,size.z)*0.57;
const aspect = innerWidth/innerHeight;
const camera = new THREE.OrthographicCamera(-extent*aspect,extent*aspect,extent,-extent,0.1,10000);
const direction = view==='top'||silhouette ? new THREE.Vector3(0,1,0) : view==='side' ? new THREE.Vector3(1,0,0) : view==='rear' ? new THREE.Vector3(0,0,-1) : view==='front' ? new THREE.Vector3(0,0,1) : new THREE.Vector3(1,0.7,1.2).normalize();
if(view==='top'||silhouette) camera.up.set(0,0,1);
camera.position.copy(center).addScaledVector(direction,extent*5);camera.lookAt(center);
const renderer = new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(1);renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.outputColorSpace=THREE.SRGBColorSpace;document.body.append(renderer.domElement);
renderer.render(scene,camera);
document.body.dataset.ready='true';
document.body.dataset.triangles=String(renderer.info.render.triangles);
document.body.dataset.calls=String(renderer.info.render.calls);
